name: Mortal
version: '${project.version}'
author: Hammzar
main: me.hamza.pillarsoffortune.Mortal
api-version: '1.21'
description: '${project.description}'
commands:
  mortal:
    description: Main Command of the core
    usage: /mortal
    aliases:
      - pillarsoffortune
  arena:
    description: Arena management commands
    usage: /arena <add|remove|list|teleport>
    permission: mortal.arena
  tntcart:
    description: TNT cart commands
    usage: /tntcart
    permission: mortal.tntcart
  buildmode:
    description: Build mode commands
    usage: /build
    permission: mortal.buildmode
  setlobby:
    description: Set the lobby
    usage: /setlobby
    permission: mortal.setlobby

