name: POF
version: '${project.version}'
main: me.hamza.pillarsoffortune.POF
api-version: '1.21'
commands:
  arena:
    description: Arena management commands
    usage: /arena <add|remove|list|teleport>
    permission: pof.arena