name: POF
version: '${project.version}'
author: Hammzar
main: me.hamza.pillarsoffortune.POF
api-version: '1.21'
commands:
  pof:
    description: Main Command of the core
    usage: /pof
    aliases:
      - pillarsoffortune
  arena:
    description: Arena management commands
    usage: /arena <add|remove|list|teleport>
    permission: pof.arena
